// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/shortener.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalURL   string                 `protobuf:"bytes,1,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLRequest) Reset() {
	*x = GetShortURLRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLRequest) ProtoMessage() {}

func (x *GetShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLRequest.ProtoReflect.Descriptor instead.
func (*GetShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *GetShortURLRequest) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type GetShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLResponse) Reset() {
	*x = GetShortURLResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLResponse) ProtoMessage() {}

func (x *GetShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLResponse.ProtoReflect.Descriptor instead.
func (*GetShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *GetShortURLResponse) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalURL   string                 `protobuf:"bytes,1,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type OriginalURLWithID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalURL   string                 `protobuf:"bytes,1,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	CorrelationID string                 `protobuf:"bytes,2,opt,name=correlationID,proto3" json:"correlationID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginalURLWithID) Reset() {
	*x = OriginalURLWithID{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalURLWithID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalURLWithID) ProtoMessage() {}

func (x *OriginalURLWithID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalURLWithID.ProtoReflect.Descriptor instead.
func (*OriginalURLWithID) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *OriginalURLWithID) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

func (x *OriginalURLWithID) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

type GetShortURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalURLs  []*OriginalURLWithID   `protobuf:"bytes,1,rep,name=originalURLs,proto3" json:"originalURLs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLsRequest) Reset() {
	*x = GetShortURLsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLsRequest) ProtoMessage() {}

func (x *GetShortURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLsRequest.ProtoReflect.Descriptor instead.
func (*GetShortURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortURLsRequest) GetOriginalURLs() []*OriginalURLWithID {
	if x != nil {
		return x.OriginalURLs
	}
	return nil
}

type ShortURLWithID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	CorrelationID string                 `protobuf:"bytes,2,opt,name=correlationID,proto3" json:"correlationID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLWithID) Reset() {
	*x = ShortURLWithID{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLWithID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLWithID) ProtoMessage() {}

func (x *ShortURLWithID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLWithID.ProtoReflect.Descriptor instead.
func (*ShortURLWithID) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *ShortURLWithID) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *ShortURLWithID) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

type GetShortURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURLs     []*ShortURLWithID      `protobuf:"bytes,1,rep,name=shortURLs,proto3" json:"shortURLs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLsResponse) Reset() {
	*x = GetShortURLsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLsResponse) ProtoMessage() {}

func (x *GetShortURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLsResponse.ProtoReflect.Descriptor instead.
func (*GetShortURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetShortURLsResponse) GetShortURLs() []*ShortURLWithID {
	if x != nil {
		return x.ShortURLs
	}
	return nil
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{8}
}

type ShortOriginalURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`
	OriginalURL   string                 `protobuf:"bytes,2,opt,name=OriginalURL,proto3" json:"OriginalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortOriginalURL) Reset() {
	*x = ShortOriginalURL{}
	mi := &file_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortOriginalURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortOriginalURL) ProtoMessage() {}

func (x *ShortOriginalURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortOriginalURL.ProtoReflect.Descriptor instead.
func (*ShortOriginalURL) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *ShortOriginalURL) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *ShortOriginalURL) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type GetUserURLsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShortOriginalURLs []*ShortOriginalURL    `protobuf:"bytes,1,rep,name=shortOriginalURLs,proto3" json:"shortOriginalURLs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserURLsResponse) GetShortOriginalURLs() []*ShortOriginalURL {
	if x != nil {
		return x.ShortOriginalURLs
	}
	return nil
}

type MarkRecordsForDeletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURLs     []string               `protobuf:"bytes,1,rep,name=shortURLs,proto3" json:"shortURLs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRecordsForDeletionRequest) Reset() {
	*x = MarkRecordsForDeletionRequest{}
	mi := &file_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRecordsForDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRecordsForDeletionRequest) ProtoMessage() {}

func (x *MarkRecordsForDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRecordsForDeletionRequest.ProtoReflect.Descriptor instead.
func (*MarkRecordsForDeletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *MarkRecordsForDeletionRequest) GetShortURLs() []string {
	if x != nil {
		return x.ShortURLs
	}
	return nil
}

type MarkRecordsForDeletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRecordsForDeletionResponse) Reset() {
	*x = MarkRecordsForDeletionResponse{}
	mi := &file_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRecordsForDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRecordsForDeletionResponse) ProtoMessage() {}

func (x *MarkRecordsForDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRecordsForDeletionResponse.ProtoReflect.Descriptor instead.
func (*MarkRecordsForDeletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{12}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{13}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{14}
}

type GetURLsStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLsStatsRequest) Reset() {
	*x = GetURLsStatsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLsStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsStatsRequest) ProtoMessage() {}

func (x *GetURLsStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsStatsRequest.ProtoReflect.Descriptor instead.
func (*GetURLsStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{15}
}

type GetURLsStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLsStatsResponse) Reset() {
	*x = GetURLsStatsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLsStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsStatsResponse) ProtoMessage() {}

func (x *GetURLsStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsStatsResponse.ProtoReflect.Descriptor instead.
func (*GetURLsStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *GetURLsStatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetURLsStatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\tshortener\"6\n" +
	"\x12GetShortURLRequest\x12 \n" +
	"\voriginalURL\x18\x01 \x01(\tR\voriginalURL\"1\n" +
	"\x13GetShortURLResponse\x12\x1a\n" +
	"\bshortURL\x18\x01 \x01(\tR\bshortURL\"3\n" +
	"\x15GetOriginalURLRequest\x12\x1a\n" +
	"\bshortURL\x18\x01 \x01(\tR\bshortURL\":\n" +
	"\x16GetOriginalURLResponse\x12 \n" +
	"\voriginalURL\x18\x01 \x01(\tR\voriginalURL\"[\n" +
	"\x11OriginalURLWithID\x12 \n" +
	"\voriginalURL\x18\x01 \x01(\tR\voriginalURL\x12$\n" +
	"\rcorrelationID\x18\x02 \x01(\tR\rcorrelationID\"W\n" +
	"\x13GetShortURLsRequest\x12@\n" +
	"\foriginalURLs\x18\x01 \x03(\v2\x1c.shortener.OriginalURLWithIDR\foriginalURLs\"R\n" +
	"\x0eShortURLWithID\x12\x1a\n" +
	"\bshortURL\x18\x01 \x01(\tR\bshortURL\x12$\n" +
	"\rcorrelationID\x18\x02 \x01(\tR\rcorrelationID\"O\n" +
	"\x14GetShortURLsResponse\x127\n" +
	"\tshortURLs\x18\x01 \x03(\v2\x19.shortener.ShortURLWithIDR\tshortURLs\"\x14\n" +
	"\x12GetUserURLsRequest\"P\n" +
	"\x10ShortOriginalURL\x12\x1a\n" +
	"\bShortURL\x18\x01 \x01(\tR\bShortURL\x12 \n" +
	"\vOriginalURL\x18\x02 \x01(\tR\vOriginalURL\"`\n" +
	"\x13GetUserURLsResponse\x12I\n" +
	"\x11shortOriginalURLs\x18\x01 \x03(\v2\x1b.shortener.ShortOriginalURLR\x11shortOriginalURLs\"=\n" +
	"\x1dMarkRecordsForDeletionRequest\x12\x1c\n" +
	"\tshortURLs\x18\x01 \x03(\tR\tshortURLs\" \n" +
	"\x1eMarkRecordsForDeletionResponse\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x15\n" +
	"\x13GetURLsStatsRequest\"@\n" +
	"\x14GetURLsStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users2\xc8\x04\n" +
	"\tShortener\x12L\n" +
	"\vGetShortURL\x12\x1d.shortener.GetShortURLRequest\x1a\x1e.shortener.GetShortURLResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortener.GetOriginalURLRequest\x1a!.shortener.GetOriginalURLResponse\x12O\n" +
	"\fGetShortURLs\x12\x1e.shortener.GetShortURLsRequest\x1a\x1f.shortener.GetShortURLsResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortener.GetUserURLsRequest\x1a\x1e.shortener.GetUserURLsResponse\x12m\n" +
	"\x16MarkRecordsForDeletion\x12(.shortener.MarkRecordsForDeletionRequest\x1a).shortener.MarkRecordsForDeletionResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponse\x12O\n" +
	"\fGetURLsStats\x12\x1e.shortener.GetURLsStatsRequest\x1a\x1f.shortener.GetURLsStatsResponseB\x16Z\x14internal/app/grpcapib\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shortener_proto_goTypes = []any{
	(*GetShortURLRequest)(nil),             // 0: shortener.GetShortURLRequest
	(*GetShortURLResponse)(nil),            // 1: shortener.GetShortURLResponse
	(*GetOriginalURLRequest)(nil),          // 2: shortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),         // 3: shortener.GetOriginalURLResponse
	(*OriginalURLWithID)(nil),              // 4: shortener.OriginalURLWithID
	(*GetShortURLsRequest)(nil),            // 5: shortener.GetShortURLsRequest
	(*ShortURLWithID)(nil),                 // 6: shortener.ShortURLWithID
	(*GetShortURLsResponse)(nil),           // 7: shortener.GetShortURLsResponse
	(*GetUserURLsRequest)(nil),             // 8: shortener.GetUserURLsRequest
	(*ShortOriginalURL)(nil),               // 9: shortener.ShortOriginalURL
	(*GetUserURLsResponse)(nil),            // 10: shortener.GetUserURLsResponse
	(*MarkRecordsForDeletionRequest)(nil),  // 11: shortener.MarkRecordsForDeletionRequest
	(*MarkRecordsForDeletionResponse)(nil), // 12: shortener.MarkRecordsForDeletionResponse
	(*PingRequest)(nil),                    // 13: shortener.PingRequest
	(*PingResponse)(nil),                   // 14: shortener.PingResponse
	(*GetURLsStatsRequest)(nil),            // 15: shortener.GetURLsStatsRequest
	(*GetURLsStatsResponse)(nil),           // 16: shortener.GetURLsStatsResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	4,  // 0: shortener.GetShortURLsRequest.originalURLs:type_name -> shortener.OriginalURLWithID
	6,  // 1: shortener.GetShortURLsResponse.shortURLs:type_name -> shortener.ShortURLWithID
	9,  // 2: shortener.GetUserURLsResponse.shortOriginalURLs:type_name -> shortener.ShortOriginalURL
	0,  // 3: shortener.Shortener.GetShortURL:input_type -> shortener.GetShortURLRequest
	2,  // 4: shortener.Shortener.GetOriginalURL:input_type -> shortener.GetOriginalURLRequest
	5,  // 5: shortener.Shortener.GetShortURLs:input_type -> shortener.GetShortURLsRequest
	8,  // 6: shortener.Shortener.GetUserURLs:input_type -> shortener.GetUserURLsRequest
	11, // 7: shortener.Shortener.MarkRecordsForDeletion:input_type -> shortener.MarkRecordsForDeletionRequest
	13, // 8: shortener.Shortener.Ping:input_type -> shortener.PingRequest
	15, // 9: shortener.Shortener.GetURLsStats:input_type -> shortener.GetURLsStatsRequest
	1,  // 10: shortener.Shortener.GetShortURL:output_type -> shortener.GetShortURLResponse
	3,  // 11: shortener.Shortener.GetOriginalURL:output_type -> shortener.GetOriginalURLResponse
	7,  // 12: shortener.Shortener.GetShortURLs:output_type -> shortener.GetShortURLsResponse
	10, // 13: shortener.Shortener.GetUserURLs:output_type -> shortener.GetUserURLsResponse
	12, // 14: shortener.Shortener.MarkRecordsForDeletion:output_type -> shortener.MarkRecordsForDeletionResponse
	14, // 15: shortener.Shortener.Ping:output_type -> shortener.PingResponse
	16, // 16: shortener.Shortener.GetURLsStats:output_type -> shortener.GetURLsStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
